### ISSUE TITLE
psd_matrix

### ISSUE THREAD

**Issue by Lionyd** [Zanue/SpectrumPrediction#1]
There seems to be no original matlab file here(psd_matrix).
Can you share the original data file in the code.
Thank you very much indeed.

**Comment by Zanue** [comment]
Hi, the original data is a sequence of complex numbers, representing the time-domain sequence of the signal. The results of STFT of the original sequence are stored in "𝑝𝑠𝑑. 𝑚𝑎𝑡". In which "psd_matrix" represents the power spectral density matrix, where the first dimension represents the frequency domain, the second dimension represents the time domain, and each element is in dB/Hz.

Hope this helps you!
